### ISSUE TITLE
i'm on ezETH (Zircuit) i want to go ezETH Arbitrum but don't swicth

### ISSUE THREAD

**Issue by defoxy-dev** [pendle-finance/pendle-core-v2-public#11]
![bugPandle](https://github.com/pendle-finance/pendle-core-v2-public/assets/77142492/aa281e9c-8424-4626-847a-f822d2e9362f)

**Comment by ayobuenavista** [comment]
Please do not send support requests on our public repo. Kindly go to our Discord.
