### ISSUE TITLE
Pendle Finance

### ISSUE THREAD

**Issue by Smithy1946** [pendle-finance/pendle-core-v2-public#9]
The following transfer was sent to Pendle.  It says it has been reverted but has not been received yet.  Please help.

Crypto: ETH
Amount: 0.50955107 ETH
Fee: 0.0033ETH
Address: 0xE05be3F691EBC9DcB1B8F781695F4379F2f0aF6C
TxID: 0x847e65b98c9f3ba449585a1ec4a57505377730cf91aee0acfe93a5e66aa947d0

0xE05-0aF6C
Ethereum Address
0xE05be3F691EBC9DcB1B8F781695F4379F2f0aF6C
Ethereum Balance
0.503084405098288245
•
$1,327.93
WalletTokens
Summary
This address has transacted 3 times on the Ethereum blockchain. It has received a total of 0.50625107 ETH $1,336.29 and has sent a total of 0.00 ETH $0.00 The current value of this address is 0.503084405098288245 ETH $1,327.93.
USDT
Token Portfolio
•1
Total Received
0.50625107 ETH
$1,336.29
Total Sent
0.00 ETH
$0.00
Total Volume
0.50625107 ETH
$1,336.29

![image](https://github.com/pendle-finance/pendle-core-v2-public/assets/160082893/78d6f1dd-455e-4552-b7ed-4aecfe5b4c3b)

**Comment by ayobuenavista** [comment]
Please do not submit support requests on our public repo. Kindly go to our Discord.
